### ISSUE TITLE
Editable cells

### ISSUE THREAD

**Issue by pzygielo** [woozny/paragony#7]
With current version (c31f44a088c2c1cf6e02861a34bdeddf73fdd658) it's possible to select one cell in the table and edit in-place. Cell's value can be updated, however such change is not persisted. We're left with presented values that do not reflect stored state.

We could
1. handle in-place edits (IMO that would be cool)
2. or stick to already implemented edit action and disable in-place edits.

**Comment by woozny** [comment]
I think for now we should stay with current edditing mode and disable table edditing, as I have put a lot of effort to create it :)
